spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://sql7.freemysqlhosting.net:3306/sql7286629
    username: sql7286629
    password: pjfQgt9MSZ
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

